version: "3.7"

services:
  web:
    container_name: apps
    build: .
    command: sh -c "
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py collectstatic --no-input &&
      python3 manage.py process_tasks &
      gunicorn news.wsgi:application --timeout=256 --workers=2 -b 0.0.0.0 -p 8000"
    volumes:
      - static_volume:/app/storage        
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure

  db:
    container_name: news_db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .db.env
    

volumes:
  postgres_data:
  static_volume:
  media_volume: